//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Models.OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseStatistics
    {
        public int PSId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual User Users { get; set; }
    }
}
