//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Models.StoreDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int BasketId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual User Users { get; set; }
    }
}
